<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChucNangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('chuc_nangs')->delete();
        DB::table('chuc_nangs')->truncate();
        DB::table('chuc_nangs')->insert([
            ['id' => 1, 'ten_chuc_nang' => 'Export excel admin'],
            ['id' => 2, 'ten_chuc_nang' => 'Add news admin'],
            ['id' => 3, 'ten_chuc_nang' => 'Get data admin'],
            ['id' => 4, 'ten_chuc_nang' => 'Change password admin'],
            ['id' => 5, 'ten_chuc_nang' => 'Update admin'],
            ['id' => 6, 'ten_chuc_nang' => 'Delete admin'],
            ['id' => 7, 'ten_chuc_nang' => 'Change status admin'],
            ['id' => 8, 'ten_chuc_nang' => 'Create QR Code Table'],
            ['id' => 9, 'ten_chuc_nang' => 'Create permission'],
            ['id' => 10, 'ten_chuc_nang' => 'Get data permission'],
            ['id' => 11, 'ten_chuc_nang' => 'Change status permission'],
            ['id' => 12, 'ten_chuc_nang' => 'Update permission'],
            ['id' => 13, 'ten_chuc_nang' => 'Delete permission'],
            ['id' => 14, 'ten_chuc_nang' => 'Get working day data'],
            ['id' => 15, 'ten_chuc_nang' => 'Register your work schedule'],
            ['id' => 16, 'ten_chuc_nang' => 'Update your work schedule'],
            ['id' => 17, 'ten_chuc_nang' => 'Create categories'],
            ['id' => 18, 'ten_chuc_nang' => 'Change status categories'],
            ['id' => 19, 'ten_chuc_nang' => 'Get data categories'],
            ['id' => 20, 'ten_chuc_nang' => 'Update categories'],
            ['id' => 21, 'ten_chuc_nang' => 'Delete categories'],
            ['id' => 22, 'ten_chuc_nang' => 'Search categories'],
            ['id' => 23, 'ten_chuc_nang' => 'Create area'],
            ['id' => 24, 'ten_chuc_nang' => 'Get data area'],
            ['id' => 25, 'ten_chuc_nang' => 'Update area'],
            ['id' => 26, 'ten_chuc_nang' => 'Delete area'],
            ['id' => 27, 'ten_chuc_nang' => 'Change status area'],
            ['id' => 28, 'ten_chuc_nang' => 'Create dish'],
            ['id' => 29, 'ten_chuc_nang' => 'Get data dish'],
            ['id' => 30, 'ten_chuc_nang' => 'Change status dish'],
            ['id' => 31, 'ten_chuc_nang' => 'Update dish'],
            ['id' => 32, 'ten_chuc_nang' => 'Delete dish'],
            ['id' => 33, 'ten_chuc_nang' => 'Create table'],
            ['id' => 34, 'ten_chuc_nang' => 'Get data table'],
            ['id' => 35, 'ten_chuc_nang' => 'Change status table'],
            ['id' => 36, 'ten_chuc_nang' => 'Update table'],
            ['id' => 37, 'ten_chuc_nang' => 'Delete table'],
            ['id' => 38, 'ten_chuc_nang' => 'Search data table'],
            ['id' => 39, 'ten_chuc_nang' => 'Get dish data by table'],
            ['id' => 40, 'ten_chuc_nang' => 'Fold the table'],
            ['id' => 41, 'ten_chuc_nang' => 'Get data supplier'],
            ['id' => 42, 'ten_chuc_nang' => 'Search data supplier'],
            ['id' => 43, 'ten_chuc_nang' => 'Create supplier'],
            ['id' => 44, 'ten_chuc_nang' => 'Delete supplier'],
            ['id' => 45, 'ten_chuc_nang' => 'Update supplier'],
            ['id' => 46, 'ten_chuc_nang' => 'Change status supplier'],
            ['id' => 47, 'ten_chuc_nang' => 'Get data article category'],
            ['id' => 48, 'ten_chuc_nang' => 'Create article category'],
            ['id' => 49, 'ten_chuc_nang' => 'Delete article category'],
            ['id' => 50, 'ten_chuc_nang' => 'Update article category'],
            ['id' => 51, 'ten_chuc_nang' => 'Change status article category'],
            ['id' => 52, 'ten_chuc_nang' => 'Search article category'],
            ['id' => 53, 'ten_chuc_nang' => 'Get data posts'],
            ['id' => 54, 'ten_chuc_nang' => 'Search data posts'],
            ['id' => 55, 'ten_chuc_nang' => 'Create posts'],
            ['id' => 56, 'ten_chuc_nang' => 'Delete posts'],
            ['id' => 57, 'ten_chuc_nang' => 'Update posts'],
            ['id' => 58, 'ten_chuc_nang' => 'Get data by region'],
            ['id' => 59, 'ten_chuc_nang' => 'Create table and bill'],
            ['id' => 60, 'ten_chuc_nang' => 'Get the invoice code'],
            ['id' => 61, 'ten_chuc_nang' => 'Update table detail data according to invoices'],
            ['id' => 62, 'ten_chuc_nang' => 'Delete table detail data according to invoice'],
            ['id' => 63, 'ten_chuc_nang' => 'Update sales invoices'],
            ['id' => 64, 'ten_chuc_nang' => 'Delete table'],
            ['id' => 65, 'ten_chuc_nang' => 'Create ingredient'],
            ['id' => 66, 'ten_chuc_nang' => 'Create ingredient'],
            ['id' => 67, 'ten_chuc_nang' => 'Create ingredient'],
            ['id' => 68, 'ten_chuc_nang' => 'Create ingredient'],
            ['id' => 69, 'ten_chuc_nang' => 'Create ingredient'],
            ['id' => 70, 'ten_chuc_nang' => 'Create ingredient'],
            ['id' => 71, 'ten_chuc_nang' => 'Get data bill by table'],
            ['id' => 72, 'ten_chuc_nang' => 'Get data bill'],
            ['id' => 73, 'ten_chuc_nang' => 'Get data invoice details'],
            ['id' => 74, 'ten_chuc_nang' => 'Export excel bill'],
            ['id' => 75, 'ten_chuc_nang' => 'Get transaction history data'],
            ['id' => 76, 'ten_chuc_nang' => 'Create customer'],
            ['id' => 77, 'ten_chuc_nang' => 'Update customer'],
            ['id' => 78, 'ten_chuc_nang' => 'Delete customer'],
            ['id' => 79, 'ten_chuc_nang' => 'Get customer'],
            ['id' => 80, 'ten_chuc_nang' => 'Search customer'],
            ['id' => 81, 'ten_chuc_nang' => 'Get data customer'],
            ['id' => 82, 'ten_chuc_nang' => 'Get data salary'],
            ['id' => 83, 'ten_chuc_nang' => 'Update rose staff'],
            ['id' => 84, 'ten_chuc_nang' => 'Update status done'],
            ['id' => 85, 'ten_chuc_nang' => 'Get detail workday'],
            ['id' => 86, 'ten_chuc_nang' => 'Get data Material'],
            ['id' => 87, 'ten_chuc_nang' => 'Create Material'],
            ['id' => 88, 'ten_chuc_nang' => 'Update warehousing'],
            ['id' => 89, 'ten_chuc_nang' => 'Delete Material Material'],
            ['id' => 90, 'ten_chuc_nang' => 'Create a warehousing invoice'],
            ['id' => 91, 'ten_chuc_nang' => 'Get a warehousing invoice'],
            ['id' => 92, 'ten_chuc_nang' => 'Get detail warehousing invoice'],
            ['id' => 93, 'ten_chuc_nang' => 'Export warehousing invoice'],
            ['id' => 94, 'ten_chuc_nang' => 'Get data Inventory'],
            ['id' => 95, 'ten_chuc_nang' => 'Update data Inventory'],
            ['id' => 96, 'ten_chuc_nang' => 'Create code voucher'],
            ['id' => 97, 'ten_chuc_nang' => 'Get data code voucher'],
            ['id' => 98, 'ten_chuc_nang' => 'Update status code voucher'],
            ['id' => 99, 'ten_chuc_nang' => 'Update code voucher'],
            ['id' => 100, 'ten_chuc_nang' => 'Delete code voucher'],
            ['id' => 101, 'ten_chuc_nang' => 'Statistics'],
            ['id' => 102, 'ten_chuc_nang' => 'Turnover'],
            ['id' => 107, 'ten_chuc_nang' => 'View admin'],
            ['id' => 108, 'ten_chuc_nang' => 'View customer'],
            ['id' => 109, 'ten_chuc_nang' => 'View Permission'],
            ['id' => 110, 'ten_chuc_nang' => 'View Categories'],
            ['id' => 111, 'ten_chuc_nang' => 'View area'],
            ['id' => 112, 'ten_chuc_nang' => 'View dish'],
            ['id' => 113, 'ten_chuc_nang' => 'View table'],
            ['id' => 114, 'ten_chuc_nang' => 'View suppliers'],
            ['id' => 115, 'ten_chuc_nang' => 'View article category'],
            ['id' => 116, 'ten_chuc_nang' => 'View article'],
            ['id' => 117, 'ten_chuc_nang' => 'View work schedule'],
            ['id' => 118, 'ten_chuc_nang' => 'View sales invoice'],
            ['id' => 119, 'ten_chuc_nang' => 'View material'],
            ['id' => 120, 'ten_chuc_nang' => 'View employee salary'],
            ['id' => 121, 'ten_chuc_nang' => 'View enter warehouse'],
            ['id' => 122, 'ten_chuc_nang' => 'View warehouse Invoice'],
            ['id' => 123, 'ten_chuc_nang' => 'View code voucher'],
            ['id' => 124, 'ten_chuc_nang' => 'View statistics'],
            ['id' => 125, 'ten_chuc_nang' => 'View inventory'],
            ['id' => 126, 'ten_chuc_nang' => 'View turnover'],
            ['id' => 127, 'ten_chuc_nang' => 'View material'],
            ['id' => 128, 'ten_chuc_nang' => 'View use of the service'],
        ]);
    }
}
